# Generated by Django 4.2.19 on 2025-02-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisist',
            new_name='PageVisits',
        ),
    ]
